### ISSUE TITLE
Backdating of transactions is not possible

### ISSUE THREAD

**Issue by Knoedelauflauf** [nicktylah/gnucash-mobile#3]
Hey,

Currently, it is not possible to backdate a new transaction in the iOS version. Whenever I change the date field in the New Transaction form, it immediately falls back to the current date. I would expect the date I selected to be displayed.

Greetings,

knoedelauflauf

**Comment by nicktylah** [comment]
Resolved in [1.0.4](https://github.com/nicktylah/gnucash-mobile/releases/tag/1.0.4). Thanks for the feedback 👍
